### ISSUE TITLE
能否出个windows的demo ?

### ISSUE THREAD

**Issue by how0723** [breadbread1984/Caffe2-C-demo#2]
能否出个windows的demo ?

**Comment by breadbread1984** [comment]
windows下面据我所知，虽然可能成功编译caffe2，但是都无法正常运行。所以windows版本没有意义。

**Comment by SyGoing** [comment]
搞了几天确实发现windows下很多问题，虽然提供了编译文件，但是
workspace.RunNetOnce(init_net);就出错，追进去看空指针：
0x00007FFFCC9DA388 处(位于 caffe2_C++_Test.exe 中)有未经处理的异常: Microsoft C++ 异常: caffe2::EnforceNotMet，位于内存位置 0x0000004955D4F750 处

**Comment by breadbread1984** [comment]
caffe2好像不能在windows上跑。现在都在用pytorch 1.0。也可以直接用c++训练。应该升级了。
