### ISSUE TITLE
are you available for freelancing

### ISSUE THREAD

**Issue by ghost** [breadbread1984/Caffe2-C-demo#5]
.

**Comment by breadbread1984** [comment]
are you hiring me?

**Comment by deepseek** [comment]
are you interested?

**Comment by breadbread1984** [comment]
I am having a tight schedule recently. but we can keep in touch. you can contact me through the email show at my profile.

**Comment by ghost** [comment]
I have sent you an email, have a look.
Reply back to me there, so we can reach an agreement
